name: Publish to PyPI
on: push
jobs:
  build-and-publish:
    # only publish to PyPI on tag pushes
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y just
      - name: Checkout sources
        uses: actions/checkout@v6
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
      - name: Initialize the working copy
        run: |
          just init
      - name: Build and publish to PyPI
        run: |
          just publish
